In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
import os

/home/ec2-user/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


# Loading data

In [2]:
direc=os.path.dirname(os.path.realpath('__file__'))
os.path.join(direc)
table = pd.read_csv("category_prediction.csv", names=['userId','age','sex','date','dayofweek','amount','geoId','catId','title'])
table = table.sort_values(by='date')
table['catId'].astype(int)
table['date'] = pd.to_datetime(table['date'], format='%Y-%m-%d')
table = table.set_index(['date'])

print table

                     userId  age  sex  dayofweek  amount       geoId   catId  \
date                                                                           
2018-01-01 00:00:04  537425   56    0          2    3900   서울특별시 종로구  321110   
2018-01-01 00:00:06  484684   32    1          2   10800   서울특별시 양천구  241410   
2018-01-01 00:00:17  484684   32    1          2    9500   서울특별시 양천구  241112   
2018-01-01 00:00:47  484684   32    1          2    2400   서울특별시 동작구  321110   
2018-01-01 00:01:56  545830   52    1          2    4500   서울특별시 도봉구  321110   
2018-01-01 00:02:11  534536   47    0          2   22200   서울특별시 노원구  221210   
2018-01-01 00:02:42  517178   41    0          2    8500   서울특별시 금천구  321110   
2018-01-01 00:02:56  282786   32    1          2    9370   서울특별시 관악구  321110   
2018-01-01 00:03:01  490638   57    0          2    3120  서울특별시 영등포구  321110   
2018-01-01 00:03:14  449134   36    0          2    7000   서울특별시 은평구  561110   
2018-01-01 00:05:28  494586   49    1   

# Category filtering:: 외식,유흥,문화예술,뷰티

In [3]:
#외식/유흥/문화예술/뷰티
table = table.query('(catId >= 220000 and catId <=240000) or (catId>=260000 and catId<=270000) or (catId>=560000 and catId<=570000) or (catId>=460000 and catId<= 470000)')
print table


                     userId  age  sex  dayofweek  amount       geoId   catId  \
date                                                                           
2018-01-01 00:02:11  534536   47    0          2   22200   서울특별시 노원구  221210   
2018-01-01 00:03:14  449134   36    0          2    7000   서울특별시 은평구  561110   
2018-01-01 00:09:12  501328   31    0          2   79000   서울특별시 중랑구  221111   
2018-01-01 00:09:13  491320   50    1          2   38000   서울특별시 중랑구  261310   
2018-01-01 00:09:21  143856   36    1          2    8000   서울특별시 용산구  221810   
2018-01-01 00:10:58  539205   28    1          2   25500   서울특별시 종로구  221815   
2018-01-01 00:11:32  423819   30    1          2    5500   서울특별시 강남구  261310   
2018-01-01 00:12:53  218341   23    0          2   16000   서울특별시 송파구  222113   
2018-01-01 00:13:37  489516   32    1          2   18000   서울특별시 성동구  561110   
2018-01-01 00:13:58  421620   37    0          2    8000   서울특별시 마포구  261310   
2018-01-01 00:14:24  354398   34    1   

# Input scaling

In [4]:
#min-max scaling
epsilon = 0.00000000001
print table['amount'].min()
print table['amount'].max()

#table['age'] =    ( table['age'] - table['age'].min() ) /( table['age'].max()-table['age'].min()+epsilon)
table['amount'] = (table['amount'] - table['amount'].min() ) / (table['amount'].max() - table['amount'].min() + epsilon )


1
254100000


# Hyper parameters

In [5]:
factorized_cat = pd.factorize(np.array(table['catId']))
factorized_geo = pd.factorize(np.array(table['geoId']))

original_cat={}
leng = len(factorized_cat[0])
catList = table['catId']

for i in range(0,leng):
    original_cat[ factorized_cat[0][i] ] = catList[i]
    
#params
table['catId'] = factorized_cat[0] 
catMin = int(table.agg({'catId':'min'}))
catMax = int(table.agg({'catId':'max'}))

table['geoId'] = factorized_geo[0]
geoMin = int(table.agg({'geoId':'min'}))
geoMax = int(table.agg({'geoId':'max'}))


params={}
params['catCount'] = catMax+1
params['geoCount'] = geoMax+1
params['maxLen'] = 31

params['input_size'] = 1+2+(7)+ params['catCount'] + params['geoCount']

print "Category minmax     : [%s,%s]"% (catMin,catMax)
print "Geo minmax          : [%s,%s]"% (geoMin,geoMax)
print "user Sequence       : [%s~%s]"%(0,params['maxLen']-1)



Category minmax     : [0,140]
Geo minmax          : [0,27]
user Sequence       : [0~30]


# Time window duration

In [6]:
def timerange(mode):

    if mode is 'train':
        input_s = pd.date_range(start='2018-01-01 00:00:00',periods=4,freq='10d').astype(str)
        input_e = pd.date_range(start='2018-01-31 23:59:59',periods=4,freq='10d').astype(str)
        target_s = pd.date_range(start='2018-02-01 00:00:00',periods=4,freq='10d').astype(str)
        target_e = pd.date_range(start='2018-02-10 23:59:59',periods=4,freq='10d').astype(str)
        return zip(input_s,input_e,target_s,target_e)
    
    elif mode is 'test':
        input_s = pd.date_range(start='2018-03-01 00:00:00',periods=1,freq='1d').astype(str)
        input_e = pd.date_range(start='2018-03-31 23:59:59',periods=1,freq='1d').astype(str)
        target_s = pd.date_range(start='2018-04-01 00:00:00',periods=1,freq='1d').astype(str)
        target_e = pd.date_range(start='2018-04-10 23:59:59',periods=1,freq='1d').astype(str)
        return zip(input_s,input_e,target_s,target_e)
    


# Data preprocessing with time window

In [7]:
import time
def df2seq(df,params):
    
    #dataframe to Sequence
    seq_input = []  # (batch,maxLen,input_size)
    seq_label = []  # (batch,maxLen,output_size)
    seq_mask = [] # (batch,maxLen,1)
    seq_len = []    # (batch)
    
    maxLen = params['maxLen']
    categoryCount = params['catCount']
    geoCount = params['geoCount']
     
    tp = timerange( params['mode'] )
    
    
    for s,e,ts,te in tp:

        userHistories = df.loc[s:e].groupby(['userId'])
        userFutures = df.loc[ts:te].groupby(['userId'])
        
        user_future = userFutures.groups.keys()
        user_history= userHistories.groups.keys()
           
        print s,e
        
        sss = time.time()
        for user in user_future:
        
            if user not in user_history:
                continue
            
            userData = userHistories.get_group((user))
            userTarget = userFutures.get_group((user))
            
            example = userData.loc[s:e]
            answer  = userTarget.loc[ts:te]
                        
            start_time = pd.to_datetime(s)
            end_time = pd.to_datetime(e)
            
            #user features
            sex_features = np.zeros((maxLen,2))
            age_features = np.zeros((maxLen,1))
            
            #time features
            week_features = np.zeros((maxLen,7))
            
            #transaction features
            geo_features = np.zeros((maxLen,geoCount))
            cat_features = np.zeros((maxLen,categoryCount))
            
            label = np.zeros((maxLen,categoryCount))
            
            dateList = example.index
            ageList = example['age']
            amoList = example['amount']
            sexList = example['sex']
            weekList= example['dayofweek']
            catList = example['catId']
            geoList = example['geoId']
             
            #user features
            sex_features[:,sexList[0]]=1
            age_features[:,0] = ageList[0]
            
            #time feature
            dayofweek_s = start_time.dayofweek
            for day in range(maxLen):
                week_features[day][(dayofweek_s + day)%7]=1
            
            #transaction features
            length = len(dateList)
            for t in range(length):
                today = (dateList[t]-start_time).days
                past = range( max(0, today-10),today)
                label[past , [ catList[t] ] * len(past) ]=1 
                geo_features[today][geoList[t]]=1
                cat_features[today][catList[t]]=1
                mask[today]=1
                
            temp = np.zeros((maxLen,0))
            temp = np.concatenate((temp,age_features),axis=1)
            temp = np.concatenate((temp,sex_features),axis=1)
            temp = np.concatenate((temp,week_features),axis=1)
            temp = np.concatenate((temp,geo_features),axis=1)
            temp = np.concatenate((temp,cat_features),axis=1)
            
            seq_input.append(temp)
            seq_label.append(label)
            seq_len.append(length)
            seq_mask.append(mask)
            
        print("--- %s seconds ---" %(time.time() - sss))
    return np.array(seq_input),np.array(seq_label),np.array(mask)


In [8]:
params['mode']='train'
seq_train_input, seq_train_label = df2seq(table,params)
print seq_train_input.shape,seq_train_label.shape

2018-01-01 2018-01-31 23:59:59
--- 72.2855429649 seconds ---
2018-01-11 2018-02-10 23:59:59
--- 72.9831211567 seconds ---
2018-01-21 2018-02-20 23:59:59
--- 87.1293208599 seconds ---
2018-01-31 2018-03-02 23:59:59
--- 68.6272041798 seconds ---
(70069, 31, 179) (70069, 31, 141)


In [9]:
params['mode']='test'
seq_test_input, seq_test_label= df2seq(table,params)
print seq_test_input.shape, seq_test_label.shape

2018-03-01 2018-03-31 23:59:59
--- 72.3880958557 seconds ---
(16550, 31, 179) (16550, 31, 141)


In [10]:
def converter(userHistories,s,e,userId,params):
    
    maxLen = params['maxLen']
    categoryCount = params['catCount']
    geoCount = params['geoCount']
     
    seq_input=[]
    userData = userHistories.get_group(userId)
    example = userData.loc[s:e]
    
    start_time = pd.to_datetime(s)
    end_time = pd.to_datetime(e)
            
    #user features
    sex_features = np.zeros((maxLen,2))
    age_features = np.zeros((maxLen,1))
            
    #time features
    week_features = np.zeros((maxLen,7))
            
    #transaction features
    geo_features = np.zeros((maxLen,geoCount))
    cat_features = np.zeros((maxLen,categoryCount))
            
    label = np.zeros((maxLen,categoryCount))
            
    dateList = example.index
    ageList = example['age']
    amoList = example['amount']
    sexList = example['sex']
    weekList= example['dayofweek']
    catList = example['catId']
    geoList = example['geoId']
             
    #user features
    sex_features[:,sexList[0]]=1
    age_features[:,0] = ageList[0]
            
    #time feature
    dayofweek_s = start_time.dayofweek
    for day in range(maxLen):
        week_features[day][(dayofweek_s + day)%7]=1
            
    #transaction features
    length = len(dateList)
    for t in range(length):
        today = (dateList[t]-start_time).days
        geo_features[today][geoList[t]]=1
        cat_features[today][catList[t]]=1
                            
    temp = np.zeros((maxLen,0))
    temp = np.concatenate((temp,age_features),axis=1)
    temp = np.concatenate((temp,sex_features),axis=1)
    temp = np.concatenate((temp,week_features),axis=1)
    temp = np.concatenate((temp,geo_features),axis=1)
    temp = np.concatenate((temp,cat_features),axis=1)
            
    seq_input.append(temp)
    
    return np.array(seq_input)

In [13]:
def lstmcell(size, prob_tensor):
    lstm_cell = tf.contrib.rnn.BasicLSTMCell(size)
    lstm_dropout = tf.contrib.rnn.DropoutWrapper(lstm_cell,output_keep_prob=prob_tensor)
    
    return lstm_dropout

max_len = params['maxLen']
input_size = params['input_size']
output_size= params['catCount']

tf.reset_default_graph()

#define lstm
sequence = tf.placeholder( tf.float32, [None, max_len, input_size ])
labels = tf.placeholder( tf.float32, [None,max_len,output_size])
keep_prob = tf.placeholder(tf.float32)

dynamic_length= tf.placeholder(tf.int32, [None])


#Model
rnn_layers = [ lstmcell(size,keep_prob) for size in [50]]
multi_rnn_cell = tf.nn.rnn_cell.MultiRNNCell(rnn_layers)
outputs,_ = tf.nn.dynamic_rnn(multi_rnn_cell, sequence , dtype=tf.float32)

#predictions = outputs
predictions = (tf.contrib.layers.fully_connected(outputs, output_size))


#print predictions.shape
topk = tf.nn.top_k(predictions,k=10,sorted=True).indices
tops = tf.nn.top_k(predictions,k=10,sorted=True).values
#
loss = tf.reduce_mean(tf.square(labels-predictions))

train = tf.train.AdamOptimizer(learning_rate= 0.0001).minimize(loss)

epochs=3000
batchSize = 4000
dataSize = 70069

sess = tf.Session()
sess.run(tf.global_variables_initializer())
sess.run(tf.local_variables_initializer())
    
for it in range(epochs):
    
    st=time.time()
    for b in range((dataSize/batchSize)):
        batch_s = b*batchSize
        batch_e = min(dataSize,batch_s + batchSize)
        l,_ = sess.run([loss,train],feed_dict={sequence: seq_train_input[batch_s:batch_e],
                                              labels:seq_train_label[batch_s:batch_e],
                                                  keep_prob:0.5} )
    closs=0
    cnt=0;
    for b in range((16550/batchSize)):
        batch_s = b*batchSize
        batch_e = min(16550,batch_s + batchSize)
        l2= sess.run(loss,feed_dict={sequence: seq_test_input[batch_s:batch_e],
                                              labels: seq_test_label[batch_s:batch_e],
                                              keep_prob:1.0})
        cnt+=1.0
        closs+=l2;
        
    closs/=cnt;
    
    
    
    print ("Loss[%s/%s]:%s  %s"%(it,epochs,closs, time.time() -st))
    if(it%10 ==0):
        userHistories = table['2018-03-01 00:00:00' : '2018-03-31 23:59:59' ].groupby(['userId'])
        test_users =  [329439,463618, 536284,551211,453264,420850,166536,
                             434771,391746,503676,178238,567126,291711]
        
        for user in test_users:
            ex = converter(userHistories,'2018-03-01 00:00:00', '2018-03-31 23:59:59',user,params)
        
            R=sess.run(topk,feed_dict={sequence: ex,keep_prob:1.0})
            R2=sess.run(tops,feed_dict={sequence: ex,keep_prob:1.0})
            
            print R[0][-1]
            print R2[0][-1]
            print '\n'
    


Loss[0/3000]:0.029947944916784763  2.27107000351
[ 93 136  81  59  78 120  67  94  58  34]
[0.580629   0.4506958  0.43890303 0.38173404 0.3736439  0.35118663
 0.3448674  0.32135305 0.31778738 0.2965713 ]


[ 93 136  81 120  78  59  58  67  94  34]
[0.5927826  0.47899702 0.43838486 0.37138224 0.36639106 0.36057198
 0.35577083 0.33376953 0.30650476 0.2883829 ]


[ 93 136  58  59  81 120  84  34  67  78]
[0.58391476 0.5319041  0.51988536 0.41654935 0.41108698 0.38276383
 0.34962502 0.29937974 0.2949144  0.2939724 ]


[ 93  58 136  59  81 120  84 135  34  78]
[0.5944151  0.5485549  0.54512936 0.41596413 0.4032308  0.38964945
 0.36398438 0.29929084 0.29017568 0.28835696]


[ 93 136  58 120  81  59  84  34 135  67]
[0.6018033  0.5679733  0.52737397 0.4215758  0.40829596 0.39053556
 0.3339144  0.31511414 0.30460554 0.30391836]


[ 93  58 136  59  81 120  84 135  34 138]
[0.5992735  0.5740126  0.558519   0.43056804 0.41661993 0.39298698
 0.38760006 0.3126803  0.2885855  0.2848375 ]


[ 93 136 

[60 18  0  1  2  3  4  5  6  7]
[0.03162606 0.01812313 0.         0.         0.         0.
 0.         0.         0.         0.        ]


[60 18 97  0  1  2  3  4  5  6]
[0.0278304  0.02300688 0.00870068 0.         0.         0.
 0.         0.         0.         0.        ]


[60  0  1  2  3  4  5  6  7  8]
[0.02051613 0.00745668 0.         0.         0.         0.
 0.         0.         0.         0.        ]


[60  0  1  2  3  4  5  6  7  8]
[0.0118457  0.00943352 0.         0.         0.         0.
 0.         0.         0.         0.        ]


[0 1 2 3 4 5 6 7 8 9]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Loss[31/3000]:0.006319464650005102  2.19864010811
Loss[32/3000]:0.006303485133685172  2.22190904617
Loss[33/3000]:0.006286986637860537  2.22210788727
Loss[34/3000]:0.006270372192375362  2.22047591209
Loss[35/3000]:0.006254844949580729  2.21008086205
Loss[36/3000]:0.006241428665816784  2.20500993729
Loss[37/3000]:0.006230309489183128  2.17781305313
Loss[38/3000]:0.006220589159056544  2.

[ 0 17  8 23 11  1  2  3  4  5]
[0.11952798 0.07137457 0.04934791 0.04365604 0.03652011 0.03299628
 0.         0.         0.         0.        ]


[ 0 17 23 11  1  8  2  3  4  5]
[0.10975415 0.04772409 0.04444119 0.03959493 0.03856243 0.03404638
 0.         0.         0.         0.        ]


[ 0 17 23  1  8 11  2  3  4  5]
[0.13236815 0.08174732 0.05030428 0.03075754 0.02805049 0.00451929
 0.         0.         0.         0.        ]


[ 0 17 23  1  8 11  2  3  4  5]
[0.12290159 0.06378783 0.05002353 0.02536657 0.01645784 0.00317971
 0.         0.         0.         0.        ]


[ 0 17 20  1 11  2  3  4  5  6]
[0.13113473 0.10142387 0.0876873  0.04714572 0.00126165 0.
 0.         0.         0.         0.        ]


Loss[71/3000]:0.006135395262390375  2.16567897797
Loss[72/3000]:0.006133433082140982  2.18648886681
Loss[73/3000]:0.0061314781196415424  2.19421815872
Loss[74/3000]:0.006129510700702667  2.19436812401
Loss[75/3000]:0.00612745329272002  2.19186878204
Loss[76/3000]:0.0061255

Loss[106/3000]:0.0060780157800763845  2.16424798965
Loss[107/3000]:0.006076773861423135  2.16620707512
Loss[108/3000]:0.006075402954593301  2.1618270874
Loss[109/3000]:0.006074103061109781  2.16391301155
Loss[110/3000]:0.006072891061194241  2.16409897804
[ 0 23  8 17 11  1 20 34  2  3]
[0.13057828 0.08004021 0.07748473 0.07698259 0.0545535  0.05250936
 0.02844814 0.01510947 0.         0.        ]


[ 0 23  1 17  8 11 20 40 34  2]
[0.13086687 0.08840856 0.08265226 0.07896008 0.07850324 0.04307194
 0.02628635 0.0149629  0.01184691 0.        ]


[ 0 17 20 23 11  8  1 39  2  3]
[0.14115658 0.09533659 0.05776097 0.05125131 0.04225159 0.01707713
 0.01295439 0.00061844 0.         0.        ]


[ 0 20 17 23  1 11  8 21 40 34]
[0.13633105 0.0840573  0.08239885 0.06878471 0.04058389 0.03751286
 0.00609225 0.00272234 0.00231341 0.00078164]


[17  0 20 11 23  8 27 34  1 60]
[0.14416662 0.13964008 0.07724074 0.05167277 0.05104693 0.02796256
 0.0176816  0.00495539 0.00391638 0.00289712]


[ 0 17 20 

[ 0 17  8 23  1 11 34 20 40  2]
[0.14947751 0.11582188 0.09615906 0.06462564 0.04197951 0.03685714
 0.02686682 0.02039741 0.01270437 0.        ]


[ 0  8 23 11  1 17 40  2  3  4]
[0.07527276 0.05835736 0.04099652 0.03075067 0.02608572 0.0169338
 0.01370634 0.         0.         0.        ]


[17  0  8 23 20  1 11 34 36  2]
[0.17852499 0.14977472 0.08896555 0.06187072 0.03967459 0.03447323
 0.03240704 0.02871997 0.02182095 0.        ]


[17  0  8 23 11 20  1 36 34 60]
[0.10339637 0.07916961 0.05799471 0.03943716 0.03169132 0.02353115
 0.02164697 0.00830171 0.00698505 0.00317099]


[ 0 20 17 23  1 11 40 21 34  8]
[0.11290494 0.07637864 0.06573807 0.0578839  0.05002541 0.03680842
 0.02922594 0.01398748 0.00701223 0.00429043]


Loss[141/3000]:0.006040773703716695  2.18815493584
Loss[142/3000]:0.006039892672561109  2.18723583221
Loss[143/3000]:0.006038965890184045  2.18575906754
Loss[144/3000]:0.006038236431777477  2.18373918533
Loss[145/3000]:0.006037379498593509  2.18684387207
Loss[146/30

Loss[174/3000]:0.006016747676767409  2.16437792778
Loss[175/3000]:0.006015844410285354  2.16542100906
Loss[176/3000]:0.006015038583427668  2.19698405266
Loss[177/3000]:0.006014241836965084  2.19136095047
Loss[178/3000]:0.0060134215746074915  2.19233489037
Loss[179/3000]:0.006012799451127648  2.19117212296
Loss[180/3000]:0.006012110388837755  2.19657206535
[ 0  8 23 17  1 11 42 31 20 21]
[0.11299767 0.07742748 0.0583287  0.03790586 0.03669518 0.03248825
 0.02059198 0.01837824 0.01125607 0.01044764]


[ 0 23  8  1 31 17 11 50 40 21]
[0.12062027 0.08525257 0.08209134 0.06913961 0.04602215 0.04431224
 0.02563282 0.01672029 0.01010171 0.00716287]


[ 0 17 31 11 23  8 20  1  2  3]
[0.11895095 0.08936071 0.02210647 0.02157288 0.01955349 0.01952716
 0.01015931 0.00435242 0.         0.        ]


[ 0 20 17 23 11  1  8 34 21 31]
[0.13898571 0.06697778 0.06376466 0.04773911 0.03000122 0.0282504
 0.02549755 0.01278458 0.01261017 0.01202277]


[17  0 20 11 27 23 42  8 60 36]
[0.16166747 0.07196619 

[17  0  8 31 23 42  1 50 11  2]
[0.07771026 0.07178624 0.0697228  0.03603334 0.02721074 0.02485394
 0.01557529 0.0096305  0.00320721 0.        ]


[ 8  0 42  1 50 31 23 11  2  3]
[0.05929866 0.05012768 0.02886326 0.02215186 0.01440794 0.01242198
 0.00904889 0.00240256 0.         0.        ]


[17  0  8 31 23 20  1 34 11 27]
[0.20186944 0.10005639 0.07312626 0.04923707 0.04800945 0.02152659
 0.01750738 0.01272531 0.01255879 0.00884091]


[17  8  0 23  1 20 42 21 31 34]
[0.10747322 0.06080237 0.03692858 0.02588969 0.02563348 0.02481011
 0.02444082 0.02357105 0.02093006 0.01417295]


[ 0 20  1 17 23 11 40 21 31 34]
[0.07626319 0.05301292 0.04937092 0.0371505  0.03521451 0.018034
 0.01718462 0.01474891 0.01295876 0.01059063]


Loss[211/3000]:0.0059921484207734466  2.17147493362
Loss[212/3000]:0.005991681944578886  2.1743209362
Loss[213/3000]:0.005991127109155059  2.17238402367
Loss[214/3000]:0.005990538164041936  2.16750001907
Loss[215/3000]:0.005989987635985017  2.16421079636
Loss[216/300

Loss[245/3000]:0.005975837353616953  2.1669549942
Loss[246/3000]:0.005975409992970526  2.16863703728
Loss[247/3000]:0.005974885541945696  2.16796088219
Loss[248/3000]:0.005974518368020654  2.16723895073
Loss[249/3000]:0.005974130588583648  2.16381502151
Loss[250/3000]:0.0059737274423241615  2.16117596626
[ 8 23  0 42 31  1 21 11 17 20]
[0.06410892 0.06096957 0.05752425 0.04258564 0.04144744 0.03460268
 0.02758137 0.02253376 0.01594138 0.00878187]


[23 31  8  1  0 17 42 40 50 21]
[0.10349466 0.09078035 0.07936065 0.0667669  0.06343324 0.02916474
 0.02863568 0.02405249 0.01392115 0.01086561]


[17  0 11 31  1 23  8 40  2  3]
[0.08685537 0.0790635  0.01343688 0.01197745 0.00829348 0.00439026
 0.00339868 0.00051953 0.         0.        ]


[ 0 20 17 31 11 23  8 34  1 21]
[0.09773564 0.05320633 0.04133219 0.02453324 0.02451391 0.02420313
 0.02171682 0.01943078 0.01565622 0.0064382 ]


[17 20 31 11 21 60 23  4  0  1]
[0.10875918 0.03427264 0.01770252 0.0153612  0.01136861 0.00705222
 0.0049

[ 8 42 31 17  1 40 23  0  2  3]
[0.04067193 0.01923344 0.01829698 0.01435756 0.01423219 0.00440606
 0.00102362 0.         0.         0.        ]


[ 8 42  1  0 31 40 11  2  3  4]
[0.0500676  0.02809804 0.02559175 0.0219803  0.00770502 0.00531305
 0.00036744 0.         0.         0.        ]


[17  8 31  0 23 34 20  1 40 42]
[0.1687044  0.06148704 0.03946717 0.0327249  0.02882713 0.01524312
 0.01498474 0.01467475 0.01002017 0.00691309]


[17  8 21 34 20 31  1  0 42 23]
[0.10832226 0.0680948  0.04614225 0.03834916 0.03246852 0.03219429
 0.0296231  0.02710774 0.02490642 0.01765197]


[ 1  0 20 34  8 40 23 11 31 21]
[0.05507101 0.05047706 0.04013334 0.02643584 0.01901207 0.01859053
 0.01746671 0.01340924 0.01316124 0.01286465]


Loss[281/3000]:0.005964832962490618  2.17572283745
Loss[282/3000]:0.005964694544672966  2.17249917984
Loss[283/3000]:0.0059640726540237665  2.18974113464
Loss[284/3000]:0.005963735398836434  2.19400501251
Loss[285/3000]:0.005963303381577134  2.15797877312
Loss[286/

Loss[316/3000]:0.005952652427367866  2.16123390198
Loss[317/3000]:0.005952601786702871  2.15759086609
Loss[318/3000]:0.00595230155158788  2.17793798447
Loss[319/3000]:0.005952022154815495  2.2011179924
Loss[320/3000]:0.005951814819127321  2.21038103104
[23  0  8 21 31  1 42 11 20 50]
[0.07787955 0.05846425 0.05218055 0.05105615 0.04531943 0.04043369
 0.03401382 0.03007579 0.01834979 0.018211  ]


[23 31  8  1 42 40  0 21  9 27]
[0.11217928 0.09120262 0.08885893 0.06678443 0.02909099 0.02298665
 0.02169189 0.01550856 0.01053037 0.00995553]


[17  0  1 40 11 31  2  3  4  5]
[0.0589292  0.03553648 0.00971159 0.00678999 0.00599221 0.00015231
 0.         0.         0.         0.        ]


[ 0 20 34 11 31  1 21 40  8 23]
[0.05517342 0.04621588 0.02560769 0.02178411 0.0202037  0.01325911
 0.00845292 0.00604527 0.00562968 0.00353709]


[ 4 17 20 11 21 34 31  0  1  2]
[0.03114761 0.02107389 0.01800605 0.00978924 0.00826913 0.007913
 0.00460086 0.         0.         0.        ]


[ 0 17 23 11 3

[ 8 42  1  0  2  3  4  5  6  7]
[0.01659016 0.01595728 0.00221803 0.         0.         0.
 0.         0.         0.         0.        ]


[ 8 42  1  0 40  9 31  2  3  4]
[0.03855049 0.02429961 0.01679689 0.00406837 0.00225534 0.00171414
 0.00075238 0.         0.         0.        ]


[17  8 31 42 34  1 40 23  0  2]
[0.10486534 0.04505108 0.01656597 0.01205667 0.00593002 0.00471247
 0.00470874 0.00239971 0.         0.        ]


[17 21  8 34 20 31 42  1 11 40]
[0.09866653 0.07003793 0.05866265 0.04164148 0.03599525 0.03095857
 0.0276725  0.02740094 0.01420215 0.00969766]


[ 1 20 34  0  8 40 21 31 11  2]
[0.05227344 0.0305732  0.02342074 0.02311742 0.01607668 0.01599945
 0.01488566 0.01098686 0.00750554 0.        ]


Loss[351/3000]:0.00594411208294332  2.166451931
Loss[352/3000]:0.005943693337030709  2.16472411156
Loss[353/3000]:0.00594313140027225  2.15930390358
Loss[354/3000]:0.005942846764810383  2.16857004166
Loss[355/3000]:0.005942447343841195  2.16456699371
Loss[356/3000]:0.00594

Loss[388/3000]:0.005931649473495781  2.16058683395
Loss[389/3000]:0.005931648425757885  2.17394804955
Loss[390/3000]:0.0059315095422789454  2.16682910919
[23 21 31  0  1 42  8  9 11 50]
[0.06838091 0.04383916 0.03032537 0.02756011 0.02749494 0.02355825
 0.02334257 0.02197572 0.02103748 0.01815741]


[ 8 23 31  1 42 27 40  9  0  2]
[0.10386052 0.0991497  0.08334354 0.05252325 0.02963853 0.01116629
 0.01078743 0.0032864  0.         0.        ]


[40  1  0  2  3  4  5  6  7  8]
[0.00326798 0.00159866 0.         0.         0.         0.
 0.         0.         0.         0.        ]


[20 34  0 11 31 40 21  1  2  3]
[0.03723984 0.02303601 0.02017996 0.0135163  0.01185006 0.00355619
 0.00262989 0.00050929 0.         0.        ]


[ 4 28 34 14 20 21  0  1  2  3]
[0.03765842 0.00724046 0.00558787 0.00243265 0.00242645 0.00187571
 0.         0.         0.         0.        ]


[ 4 11 31 21 23 50 40 34 20  9]
[0.06004315 0.02713581 0.0213699  0.01720548 0.01353005 0.01347963
 0.00934476 0.008337

[42  0  1  2  3  4  5  6  7  8]
[0.01017379 0.         0.         0.         0.         0.
 0.         0.         0.         0.        ]


[42  8  1  0  2  3  4  5  6  7]
[0.01833666 0.01666593 0.00570806 0.         0.         0.
 0.         0.         0.         0.        ]


[ 8 42  0  1  2  3  4  5  6  7]
[0.01869995 0.00509103 0.         0.         0.         0.
 0.         0.         0.         0.        ]


[21  8 42 34 17 31  1  0  2  3]
[0.05747143 0.01751927 0.01565314 0.01285341 0.00854908 0.0035055
 0.00117685 0.         0.         0.        ]


[ 1 40 21 34 20  0  2  3  4  5]
[3.7783802e-02 9.1521330e-03 2.5373567e-03 8.0146641e-04 9.9577010e-05
 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00]


Loss[421/3000]:0.005926915444433689  2.16269898415
Loss[422/3000]:0.005927191930823028  2.16277003288
Loss[423/3000]:0.005927178775891662  2.15880203247
Loss[424/3000]:0.005926954676397145  2.15807795525
Loss[425/3000]:0.005927086342126131  2.16000795364
Loss[

[42  0  1  2  3  4  5  6  7  8]
[0.00544221 0.         0.         0.         0.         0.
 0.         0.         0.         0.        ]


[42  8  1  0  2  3  4  5  6  7]
[0.01345785 0.00488952 0.0004564  0.         0.         0.
 0.         0.         0.         0.        ]


[0 1 2 3 4 5 6 7 8 9]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


[21 42  0  1  2  3  4  5  6  7]
[0.04670251 0.00687801 0.         0.         0.         0.
 0.         0.         0.         0.        ]


[ 1 40  0  2  3  4  5  6  7  8]
[0.0249854  0.00255483 0.         0.         0.         0.
 0.         0.         0.         0.        ]


Loss[461/3000]:0.0059283142909407616  2.18027806282
Loss[462/3000]:0.005928075290285051  2.19165897369
Loss[463/3000]:0.0059279948472976685  2.19447493553
Loss[464/3000]:0.005928182741627097  2.19990992546
Loss[465/3000]:0.005928670754656196  2.20919704437
Loss[466/3000]:0.005928502301685512  2.21238207817
Loss[467/3000]:0.005929136415943503  2.20673894882
Loss[468/3000]:0.005928881349

Loss[501/3000]:0.00592658540699631  2.16144609451
Loss[502/3000]:0.005926479469053447  2.16756987572
Loss[503/3000]:0.005926159908995032  2.16362094879
Loss[504/3000]:0.0059266111347824335  2.16670107841
Loss[505/3000]:0.005926209501922131  2.16753196716
Loss[506/3000]:0.005925713921897113  2.15837907791
Loss[507/3000]:0.005925894132815301  2.15869903564
Loss[508/3000]:0.005926037207245827  2.15819096565
Loss[509/3000]:0.00592571625020355  2.15690803528
Loss[510/3000]:0.005925795645453036  2.19207906723
[ 9 21 42  0  1  2  3  4  5  6]
[0.01337315 0.00354888 0.001421   0.         0.         0.
 0.         0.         0.         0.        ]


[31  8 23  1 42  0  2  3  4  5]
[0.06081547 0.05828089 0.05528498 0.01881959 0.01803412 0.
 0.         0.         0.         0.        ]


[0 1 2 3 4 5 6 7 8 9]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


[0 1 2 3 4 5 6 7 8 9]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


[0 1 2 3 4 5 6 7 8 9]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


[ 4 18 40 50  0  1  2  3  5  6]
[0.03140281 0

[0 1 2 3 4 5 6 7 8 9]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


[42  0  1  2  3  4  5  6  7  8]
[0.00939102 0.         0.         0.         0.         0.
 0.         0.         0.         0.        ]


[0 1 2 3 4 5 6 7 8 9]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


[21  0  1  2  3  4  5  6  7  8]
[0.02855186 0.         0.         0.         0.         0.
 0.         0.         0.         0.        ]


[1 0 2 3 4 5 6 7 8 9]
[0.01455126 0.         0.         0.         0.         0.
 0.         0.         0.         0.        ]


Loss[551/3000]:0.005922334035858512  2.19296216965
Loss[552/3000]:0.005921839969232678  2.19785404205
Loss[553/3000]:0.005922273267060518  2.19943094254
Loss[554/3000]:0.005922029260545969  2.20425891876
Loss[555/3000]:0.005921679898165166  2.19829893112
Loss[556/3000]:0.005921439500525594  2.19707489014
Loss[557/3000]:0.0059216105146333575  2.19630789757
Loss[558/3000]:0.005921713076531887  2.19632411003
Loss[559/3000]:0.005921788630075753  2.19640803337
Loss[560/3000]:0.0059

Loss[591/3000]:0.005919348448514938  2.17103791237
Loss[592/3000]:0.005919081158936024  2.1900510788
Loss[593/3000]:0.005919098854064941  2.18811917305
Loss[594/3000]:0.0059181449469178915  2.18681788445
Loss[595/3000]:0.00591799127869308  2.18324899673
Loss[596/3000]:0.0059176243375986814  2.17995119095
Loss[597/3000]:0.005917274160310626  2.18089294434
Loss[598/3000]:0.005918236915022135  2.17671203613
Loss[599/3000]:0.005918007111176848  2.1606760025
Loss[600/3000]:0.0059185700956732035  2.16154098511
[21  9  0  1  2  3  4  5  6  7]
[0.01622106 0.01485097 0.         0.         0.         0.
 0.         0.         0.         0.        ]


[31  8 23  1 42  6  0  2  3  4]
[0.06859065 0.05693937 0.04690095 0.02204367 0.01817574 0.00340074
 0.         0.         0.         0.        ]


[0 1 2 3 4 5 6 7 8 9]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


[40  0  1  2  3  4  5  6  7  8]
[0.00208529 0.         0.         0.         0.         0.
 0.         0.         0.         0.        ]


[0 1 2 3 

Loss[638/3000]:0.005912656895816326  2.16178679466
Loss[639/3000]:0.005912528489716351  2.15828204155
Loss[640/3000]:0.005912004737183452  2.16575503349
[21  9  0  1  2  3  4  5  6  7]
[0.02009083 0.01283717 0.         0.         0.         0.
 0.         0.         0.         0.        ]


[31  8 23  1 42  6  0  2  3  4]
[0.06428523 0.03396353 0.03037249 0.00833967 0.00752049 0.00151188
 0.         0.         0.         0.        ]


[0 1 2 3 4 5 6 7 8 9]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


[0 1 2 3 4 5 6 7 8 9]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


[0 1 2 3 4 5 6 7 8 9]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


[ 4 31 50 40  9 23 14  0  1  2]
[2.9717891e-02 2.1103069e-02 9.4194738e-03 6.1959680e-03 6.2616169e-04
 4.7482923e-04 7.7543780e-05 0.0000000e+00 0.0000000e+00 0.0000000e+00]


[0 1 2 3 4 5 6 7 8 9]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


[ 0 23  1  2  3  4  5  6  7  8]
[0.1621239  0.00523758 0.         0.         0.         0.
 0.         0.         0.         0.        ]


[0 1 2 3 4 5 6 7 8 9]

Loss[681/3000]:0.005909447558224201  2.20083880424
Loss[682/3000]:0.005910308798775077  2.20934700966
Loss[683/3000]:0.005908839753828943  2.21778416634
Loss[684/3000]:0.0059092509327456355  2.2069311142
Loss[685/3000]:0.005909149069339037  2.2043390274
Loss[686/3000]:0.005909064086154103  2.2002928257
Loss[687/3000]:0.005908913211897016  2.20149302483
Loss[688/3000]:0.005908579681999981  2.21303081512
Loss[689/3000]:0.005908363265916705  2.16975617409
Loss[690/3000]:0.005908330320380628  2.16269207001
[21  9  3  0  1  2  4  5  6  7]
[0.01699872 0.01337546 0.00041808 0.         0.         0.
 0.         0.         0.         0.        ]


[31  8 23  1 42  6  0  2  3  4]
[0.05751009 0.02567433 0.0204252  0.00980147 0.00593274 0.00101626
 0.         0.         0.         0.        ]


[0 1 2 3 4 5 6 7 8 9]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


[0 1 2 3 4 5 6 7 8 9]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


[0 1 2 3 4 5 6 7 8 9]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


[ 4 31 40 50  9  0  1  2  3  5]
[0.021

[0 1 2 3 4 5 6 7 8 9]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


[42 40  0  1  2  3  4  5  6  7]
[0.0063516 0.0006895 0.        0.        0.        0.        0.
 0.        0.        0.       ]


[0 1 2 3 4 5 6 7 8 9]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


[21  0  1  2  3  4  5  6  7  8]
[0.02161901 0.         0.         0.         0.         0.
 0.         0.         0.         0.        ]


[1 3 0 2 4 5 6 7 8 9]
[0.00600252 0.00017485 0.         0.         0.         0.
 0.         0.         0.         0.        ]


Loss[731/3000]:0.00590331747662276  2.15977597237
Loss[732/3000]:0.005903109326027334  2.16488099098
Loss[733/3000]:0.0059021321358159184  2.17946815491
Loss[734/3000]:0.005902419798076153  2.19941902161
Loss[735/3000]:0.005902687786146998  2.18669915199
Loss[736/3000]:0.005902271834202111  2.17089295387
Loss[737/3000]:0.005902141449041665  2.1719558239
Loss[738/3000]:0.005902050877921283  2.17073488235
Loss[739/3000]:0.005901806754991412  2.16914820671
Loss[740/3000]:0.005901864846237

Loss[778/3000]:0.005896536633372307  2.19619297981
Loss[779/3000]:0.005897164228372276  2.18898892403
Loss[780/3000]:0.005896973656490445  2.16736102104
[21  9  3 40  0  1  2  4  5  6]
[2.2552352e-02 1.5348832e-02 4.3172492e-03 4.7713518e-05 0.0000000e+00
 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00]


[31  8 23  1 42  6 40  0  2  3]
[0.05654228 0.03528618 0.01929338 0.01645145 0.00876653 0.00150191
 0.0009607  0.         0.         0.        ]


[0 1 2 3 4 5 6 7 8 9]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


[0 1 2 3 4 5 6 7 8 9]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


[0 1 2 3 4 5 6 7 8 9]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


[31  4 23  0 40  3 50 14  9 18]
[0.02797392 0.02222932 0.00708439 0.00680289 0.00594085 0.00214105
 0.00209769 0.00198674 0.00068294 0.00051158]


[0 1 2 3 4 5 6 7 8 9]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


[ 0 23 17  9 40  1  2  3  4  5]
[0.17439963 0.0145568  0.0020636  0.00081983 0.00073493 0.
 0.         0.         0.         0.        ]


[0 1 2 3 4 5 

Loss[817/3000]:0.005892290617339313  2.16080403328
Loss[818/3000]:0.0058923650067299604  2.16280293465
Loss[819/3000]:0.005891759064979851  2.17468309402
Loss[820/3000]:0.005890433327294886  2.16520404816
[21 17  9  3 23 50 40 28  0  1]
[0.0363163  0.02012593 0.02011392 0.00764444 0.00613495 0.00433354
 0.00390559 0.00016675 0.         0.        ]


[31  8 23  1 42 40  6  3  0  2]
[0.06614798 0.06026759 0.03933239 0.02672217 0.0190943  0.00513903
 0.00492037 0.00031364 0.         0.        ]


[17 40  9  3  0  1  2  4  5  6]
[0.0397413  0.00369058 0.00139928 0.00087489 0.         0.
 0.         0.         0.         0.        ]


[20 17 34 11  0 40 50 31  3  9]
[0.03151293 0.01650303 0.01282265 0.00932336 0.00902529 0.00811187
 0.00578939 0.0042668  0.00196748 0.00126107]


[17 20 11 34 40 14  3 18  9 31]
[0.03557879 0.02264621 0.01910275 0.00864768 0.00806728 0.00536397
 0.00217438 0.00166979 0.00141248 0.00138847]


[ 4 31 23  0 11 17 50 40 18 14]
[0.04340684 0.0366093  0.03352044 0.

[17 42  0  1  2  3  4  5  6  7]
[0.01499699 0.0033853  0.         0.         0.         0.
 0.         0.         0.         0.        ]


[42  8 31 40  3  9  1  6  0  2]
[0.01303654 0.00538206 0.00514352 0.00431001 0.00281208 0.00235154
 0.00168957 0.00089919 0.         0.        ]


[0 1 2 3 4 5 6 7 8 9]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


[21 17  0  1  2  3  4  5  6  7]
[0.03094716 0.019321   0.         0.         0.         0.
 0.         0.         0.         0.        ]


[ 1  9  3 40  0  2  4  5  6  7]
[0.01818277 0.00634217 0.00464194 0.0036514  0.         0.
 0.         0.         0.         0.        ]


Loss[851/3000]:0.005888856947422028  2.16533017159
Loss[852/3000]:0.005889186752028763  2.1676068306
Loss[853/3000]:0.005889562307856977  2.16855788231
Loss[854/3000]:0.005890282918699086  2.17835402489
Loss[855/3000]:0.005890782340429723  2.16411185265
Loss[856/3000]:0.005892066168598831  2.16048717499
Loss[857/3000]:0.0058925936464220285  2.1685590744
Loss[858/3000]:0.0058934

[17  0  1  2  3  4  5  6  7  8]
[0.00517654 0.         0.         0.         0.         0.
 0.         0.         0.         0.        ]


[42 40  3  9  0  1  2  4  5  6]
[0.00756203 0.00260675 0.00093205 0.00055186 0.         0.
 0.         0.         0.         0.        ]


[0 1 2 3 4 5 6 7 8 9]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


[21 17  0  1  2  3  4  5  6  7]
[0.01942042 0.00209245 0.         0.         0.         0.
 0.         0.         0.         0.        ]


[ 1  9  3 40  0  2  4  5  6  7]
[0.00412211 0.00287324 0.0016575  0.00035819 0.         0.
 0.         0.         0.         0.        ]


Loss[891/3000]:0.005896574817597866  2.17290401459
Loss[892/3000]:0.005896250600926578  2.16183400154
Loss[893/3000]:0.005896098213270307  2.16163492203
Loss[894/3000]:0.00589610415045172  2.16692090034
Loss[895/3000]:0.005895645706914365  2.16970491409
Loss[896/3000]:0.00589552172459662  2.17306995392
Loss[897/3000]:0.005895402864553034  2.16155219078
Loss[898/3000]:0.0058953592088073

[17 42  0  1  2  3  4  5  6  7]
[0.01135933 0.00220744 0.         0.         0.         0.
 0.         0.         0.         0.        ]


[42 40  3  9  0  1  2  4  5  6]
[0.00776703 0.00272878 0.00080838 0.00080367 0.         0.
 0.         0.         0.         0.        ]


[0 1 2 3 4 5 6 7 8 9]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


[21 17  0  1  2  3  4  5  6  7]
[0.01706296 0.0025546  0.         0.         0.         0.
 0.         0.         0.         0.        ]


[ 1  9  3 40  0  2  4  5  6  7]
[0.0093153  0.00422298 0.00223628 0.00158854 0.         0.
 0.         0.         0.         0.        ]


Loss[931/3000]:0.00589164299890399  2.16841292381
Loss[932/3000]:0.0058916357811540365  2.16234993935
Loss[933/3000]:0.005891306675039232  2.17902088165
Loss[934/3000]:0.00589132506866008  2.18748879433
Loss[935/3000]:0.00589096057228744  2.18043899536
Loss[936/3000]:0.005891154753044248  2.17850995064
Loss[937/3000]:0.005890955799259245  2.17992997169
Loss[938/3000]:0.0058908968931064

[17 42  0  1  2  3  4  5  6  7]
[0.01637482 0.00394082 0.         0.         0.         0.
 0.         0.         0.         0.        ]


[42 40  3  9  0  1  2  4  5  6]
[0.00867278 0.00279745 0.00078709 0.0006534  0.         0.
 0.         0.         0.         0.        ]


[0 1 2 3 4 5 6 7 8 9]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


[21 17  0  1  2  3  4  5  6  7]
[0.01601192 0.00386441 0.         0.         0.         0.
 0.         0.         0.         0.        ]


[ 1  9  3 40  0  2  4  5  6  7]
[0.01205163 0.005026   0.00262572 0.00251139 0.         0.
 0.         0.         0.         0.        ]


Loss[971/3000]:0.005888827727176249  2.16581487656
Loss[972/3000]:0.005888470797799528  2.16329598427
Loss[973/3000]:0.00588850537315011  2.16187286377
Loss[974/3000]:0.005888588260859251  2.16306805611
Loss[975/3000]:0.005888131679967046  2.16233301163
Loss[976/3000]:0.005888521671295166  2.15878605843
Loss[977/3000]:0.005888067418709397  2.17724490166
Loss[978/3000]:0.005888531566597

[17 42  0  1  2  3  4  5  6  7]
[0.01928066 0.00476457 0.         0.         0.         0.
 0.         0.         0.         0.        ]


[42 40  3  9  6  0  1  2  4  5]
[0.0090448  0.00324794 0.00040404 0.00037481 0.00014417 0.
 0.         0.         0.         0.        ]


[0 1 2 3 4 5 6 7 8 9]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


[21 17  0  1  2  3  4  5  6  7]
[0.01393901 0.00536792 0.         0.         0.         0.
 0.         0.         0.         0.        ]


[ 1  9 40  3  0  2  4  5  6  7]
[0.01288107 0.00562404 0.00358337 0.00276882 0.         0.
 0.         0.         0.         0.        ]


Loss[1011/3000]:0.005887274164706469  2.16755604744
Loss[1012/3000]:0.005887468112632632  2.1647400856
Loss[1013/3000]:0.0058871026849374175  2.16553807259
Loss[1014/3000]:0.005886662635020912  2.16346883774
Loss[1015/3000]:0.0058865777682513  2.19487905502
Loss[1016/3000]:0.0058867549523711205  2.18393802643
Loss[1017/3000]:0.005886979168280959  2.19039082527
Loss[1018/3000]:0.0058870

[17 42  0  1  2  3  4  5  6  7]
[0.01999976 0.0048547  0.         0.         0.         0.
 0.         0.         0.         0.        ]


[42 40  3  9  6  0  1  2  4  5]
[9.2210788e-03 3.2725967e-03 4.5844913e-04 4.1661039e-04 1.8542632e-05
 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00]


[0 1 2 3 4 5 6 7 8 9]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


[21 17  0  1  2  3  4  5  6  7]
[0.01351457 0.00578995 0.         0.         0.         0.
 0.         0.         0.         0.        ]


[ 1  9 40  3  0  2  4  5  6  7]
[0.01247013 0.00583026 0.0034821  0.00288288 0.         0.
 0.         0.         0.         0.        ]


Loss[1051/3000]:0.005885124555788934  2.20263504982
Loss[1052/3000]:0.005884288460947573  2.1964161396
Loss[1053/3000]:0.005883973557502031  2.20023298264
Loss[1054/3000]:0.005884261569008231  2.17090296745
Loss[1055/3000]:0.0058841785648837686  2.16581606865
Loss[1056/3000]:0.005884026642888784  2.16624999046
Loss[1057/3000]:0.005884183454327285  

[17 42  0  1  2  3  4  5  6  7]
[0.01735978 0.00471449 0.         0.         0.         0.
 0.         0.         0.         0.        ]


[42 40  6  9  0  1  2  3  4  5]
[8.8674687e-03 3.3032633e-03 2.0724721e-04 5.8827922e-05 0.0000000e+00
 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00]


[0 1 2 3 4 5 6 7 8 9]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


[21 17  0  1  2  3  4  5  6  7]
[0.01161051 0.00522491 0.         0.         0.         0.
 0.         0.         0.         0.        ]


[ 1  9 40  3  0  2  4  5  6  7]
[0.01081929 0.00542201 0.00350249 0.00230339 0.         0.
 0.         0.         0.         0.        ]


Loss[1091/3000]:0.005884155398234725  2.17146277428
Loss[1092/3000]:0.005881985882297158  2.16428494453
Loss[1093/3000]:0.005881354911252856  2.17159104347
Loss[1094/3000]:0.005881465971469879  2.1664121151
Loss[1095/3000]:0.005881815915927291  2.17299509048
Loss[1096/3000]:0.005882723140530288  2.17064905167
Loss[1097/3000]:0.0058837245451286435  

[17 42  0  1  2  3  4  5  6  7]
[0.02248758 0.00545289 0.         0.         0.         0.
 0.         0.         0.         0.        ]


[42 40  6  3  9  0  1  2  4  5]
[0.00989807 0.00370292 0.00047322 0.00039887 0.00018796 0.
 0.         0.         0.         0.        ]


[0 1 2 3 4 5 6 7 8 9]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


[21 17  0  1  2  3  4  5  6  7]
[0.01518674 0.00717407 0.         0.         0.         0.
 0.         0.         0.         0.        ]


[ 1  9 40  3 20  0  2  4  5  6]
[0.01360849 0.00765336 0.0051677  0.00397308 0.00137085 0.
 0.         0.         0.         0.        ]


Loss[1131/3000]:0.005882715689949691  2.20482993126
Loss[1132/3000]:0.00588383455760777  2.20082402229
Loss[1133/3000]:0.005884487414732575  2.20400691032
Loss[1134/3000]:0.005885280203074217  2.20573496819
Loss[1135/3000]:0.005885794758796692  2.20929098129
Loss[1136/3000]:0.005886691273190081  2.20262098312
Loss[1137/3000]:0.005886827362701297  2.19904088974
Loss[1138/3000]:0.0058856

[17 42  0  1  2  3  4  5  6  7]
[0.00705713 0.00302932 0.         0.         0.         0.
 0.         0.         0.         0.        ]


[42 40  0  1  2  3  4  5  6  7]
[0.0083616  0.00316501 0.         0.         0.         0.
 0.         0.         0.         0.        ]


[0 1 2 3 4 5 6 7 8 9]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


[21  0  1  2  3  4  5  6  7  8]
[0.009375 0.       0.       0.       0.       0.       0.       0.
 0.       0.      ]


[ 1  9 40  3  0  2  4  5  6  7]
[0.0075773  0.0043405  0.00294651 0.00132818 0.         0.
 0.         0.         0.         0.        ]


Loss[1171/3000]:0.005884515936486423  2.1638071537
Loss[1172/3000]:0.005883454694412649  2.17792606354
Loss[1173/3000]:0.005882292869500816  2.18118309975
Loss[1174/3000]:0.005881411605514586  2.17288899422
Loss[1175/3000]:0.005881680524908006  2.16646122932
Loss[1176/3000]:0.0058820226695388556  2.16651892662
Loss[1177/3000]:0.00588317948859185  2.17548084259
Loss[1178/3000]:0.005884258192963898  2.185

[17 42  0  1  2  3  4  5  6  7]
[0.009432   0.00479323 0.         0.         0.         0.
 0.         0.         0.         0.        ]


[42 40  6  0  1  2  3  4  5  7]
[0.00957163 0.00350464 0.00029002 0.         0.         0.
 0.         0.         0.         0.        ]


[0 1 2 3 4 5 6 7 8 9]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


[21 17  0  1  2  3  4  5  6  7]
[0.01130662 0.00119208 0.         0.         0.         0.
 0.         0.         0.         0.        ]


[ 1  9 40  3  0  2  4  5  6  7]
[0.00931799 0.00565076 0.00400782 0.00244608 0.         0.
 0.         0.         0.         0.        ]


Loss[1211/3000]:0.0058822608552873135  2.16834115982
Loss[1212/3000]:0.005882644327357411  2.17544102669
Loss[1213/3000]:0.005882459809072316  2.16965889931
Loss[1214/3000]:0.005882206605747342  2.17148804665
Loss[1215/3000]:0.005882174242287874  2.16551589966
Loss[1216/3000]:0.005883058067411184  2.16428899765
Loss[1217/3000]:0.005883089732378721  2.16234493256
Loss[1218/3000]:0.00588

[17 42 18  0  1  2  3  4  5  6]
[0.01224644 0.00451936 0.00139875 0.         0.         0.
 0.         0.         0.         0.        ]


[42 40  6  0  1  2  3  4  5  7]
[0.00912006 0.00369757 0.00032702 0.         0.         0.
 0.         0.         0.         0.        ]


[0 1 2 3 4 5 6 7 8 9]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


[21 17  0  1  2  3  4  5  6  7]
[0.01198591 0.00420998 0.         0.         0.         0.
 0.         0.         0.         0.        ]


[ 1  9 40  3 20  0  2  4  5  6]
[0.00749923 0.00664905 0.00453122 0.00277679 0.00248126 0.
 0.         0.         0.         0.        ]


Loss[1251/3000]:0.00588218797929585  2.1613740921
Loss[1252/3000]:0.005882539786398411  2.16538906097
Loss[1253/3000]:0.0058820967096835375  2.16225504875
Loss[1254/3000]:0.005881816963665187  2.18426895142
Loss[1255/3000]:0.00588236260227859  2.19570422173
Loss[1256/3000]:0.005882015568204224  2.16605901718
Loss[1257/3000]:0.005882367957383394  2.16870903969
Loss[1258/3000]:0.00588264

[17 42 18  0  1  2  3  4  5  6]
[0.02021429 0.00748654 0.00362589 0.         0.         0.
 0.         0.         0.         0.        ]


[42 40  6  9  3  8  1  0  2  4]
[0.01100515 0.0045715  0.00102267 0.00084643 0.00035629 0.00021659
 0.00019    0.         0.         0.        ]


[17  0  1  2  3  4  5  6  7  8]
[0.00917699 0.         0.         0.         0.         0.
 0.         0.         0.         0.        ]


[21 17  0  1  2  3  4  5  6  7]
[0.01288566 0.01086216 0.         0.         0.         0.
 0.         0.         0.         0.        ]


[ 1  9 40  3 20 72  0  2  4  5]
[1.1165235e-02 9.2531303e-03 6.2719975e-03 3.9438596e-03 1.6077086e-03
 3.6160462e-05 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00]


Loss[1291/3000]:0.00588573154527694  2.17143201828
Loss[1292/3000]:0.005885910126380622  2.16908121109
Loss[1293/3000]:0.005886514205485582  2.16465997696
Loss[1294/3000]:0.005886851577088237  2.16334486008
Loss[1295/3000]:0.0058874867390841246  2.16398692131

[0 1 2 3 4 5 6 7 8 9]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


[42 40  0  1  2  3  4  5  6  7]
[0.00464237 0.00208788 0.         0.         0.         0.
 0.         0.         0.         0.        ]


[17  0  1  2  3  4  5  6  7  8]
[0.0119547 0.        0.        0.        0.        0.        0.
 0.        0.        0.       ]


[21  0  1  2  3  4  5  6  7  8]
[0.00235466 0.         0.         0.         0.         0.
 0.         0.         0.         0.        ]


[ 9 40  0  1  2  3  4  5  6  7]
[0.00292049 0.00064407 0.         0.         0.         0.
 0.         0.         0.         0.        ]


Loss[1331/3000]:0.005902148084715009  2.16556096077
Loss[1332/3000]:0.005901883821934462  2.16086196899
Loss[1333/3000]:0.005901942844502628  2.16708302498
Loss[1334/3000]:0.005901784170418978  2.18458509445
Loss[1335/3000]:0.005901385564357042  2.18184399605
Loss[1336/3000]:0.00590139499399811  2.17879486084
Loss[1337/3000]:0.005901362746953964  2.17962002754
Loss[1338/3000]:0.0059009266551584

KeyboardInterrupt: 


- 0: 패스트푸드/일반
- 1: 영화
- 2: 외식/회
- 9: 맥주
- 42: 화장품
- 21: 한식뷔폐
- 17: 한식/일반
- 8 :
- 31: 일식/일반
- 23: 분식/일반
- 50: 일식/돈까스
- 40: 헤어샵

In [ ]:
original_cat


In [ ]:
test_users = [329439,463618, 536284,551211,453264,420850,166536,
                             434771,391746,503676,178238,567126,291711]

#17  8 23  0 20 31  1 40 21 11
#0 23  8  1 11 50 31 34  4 28 

table['2018-03-20':'2018-04-03'].groupby(['age']).get_group(27)
    

table.groupby(['userId']).get_group(291711)

# User Sampling


- Sampling based on user group
    - 20~25 여성 = [341770, 329439, 198995, 161617, 310756, 150409, 137363, 463618, 150409, 422341]
        
    - 20~25 남성 = [3914, 481844, 396370, 103036, 481245, 459350,272707]
        
    - 26~30 여성 = [400295, 326175, 536874, 505684, 393859, 359757, 291616, 182774, 207415,273544,420960,185077]
        
    - 26~30 남성 = [550647,	329514,343291,282759,374170,254809,515139,372982,522194,556329,441214, 503106]
        
 
 